A=input("What is your age?")
A=int(A)
if A>=16: print("You can drive")
if A>=18: print("You can vote")
if A>=21: print ("You can enjoy a beer")
if A>=55: print ("You get the senior discount")
else: print("You are so young")
